

07/07/2022 11:00:49
org.hibernate.MappingException: Foreign key (FK76794B248D7958CE:CIDADE [IDCIDADE])) must have same number of columns as the referenced primary key (CIDADE [IDCIDADE,idx])
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:90)
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:73)
	at org.hibernate.cfg.Configuration.secondPassCompileForeignKeys(Configuration.java:1263)
	at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1170)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1286)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:10)


07/07/2022 11:04:37
org.hibernate.MappingException: Foreign key (FK76794B248D7958CE:CIDADE [IDCIDADE])) must have same number of columns as the referenced primary key (CIDADE [IDCIDADE,idx])
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:90)
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:73)
	at org.hibernate.cfg.Configuration.secondPassCompileForeignKeys(Configuration.java:1263)
	at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1170)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1286)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:13)


07/07/2022 11:06:27
org.hibernate.MappingException: Foreign key (FK76794B248D7958CE:CIDADE [IDCIDADE])) must have same number of columns as the referenced primary key (CIDADE [IDCIDADE,idx])
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:90)
	at org.hibernate.mapping.ForeignKey.alignColumns(ForeignKey.java:73)
	at org.hibernate.cfg.Configuration.secondPassCompileForeignKeys(Configuration.java:1263)
	at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1170)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1286)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:13)


07/07/2022 13:33:07
org.hibernate.InvalidMappingException: Could not parse mapping document from resource beans/Cidade.hbm.xml
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:539)
	at org.hibernate.cfg.Configuration.addClass(Configuration.java:586)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:15)
Caused by: org.hibernate.PropertyNotFoundException: field [id] not found on beans.Cidade
	at org.hibernate.property.DirectPropertyAccessor.getField(DirectPropertyAccessor.java:122)
	at org.hibernate.property.DirectPropertyAccessor.getField(DirectPropertyAccessor.java:114)
	at org.hibernate.property.DirectPropertyAccessor.getGetter(DirectPropertyAccessor.java:137)
	at org.hibernate.util.ReflectHelper.getter(ReflectHelper.java:83)
	at org.hibernate.util.ReflectHelper.reflectedPropertyClass(ReflectHelper.java:71)
	at org.hibernate.mapping.SimpleValue.setTypeUsingReflection(SimpleValue.java:276)
	at org.hibernate.cfg.HbmBinder.bindSimpleId(HbmBinder.java:401)
	at org.hibernate.cfg.HbmBinder.bindRootPersistentClassCommonValues(HbmBinder.java:334)
	at org.hibernate.cfg.HbmBinder.bindRootClass(HbmBinder.java:273)
	at org.hibernate.cfg.HbmBinder.bindRoot(HbmBinder.java:144)
	at org.hibernate.cfg.Configuration.add(Configuration.java:669)
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:504)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:536)
	... 3 more


07/07/2022 13:40:02
org.hibernate.InvalidMappingException: Could not parse mapping document from resource beans/Cidade.hbm.xml
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:539)
	at org.hibernate.cfg.Configuration.addClass(Configuration.java:586)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:15)
Caused by: org.hibernate.InvalidMappingException: Could not parse mapping document from invalid mapping
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:502)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:536)
	... 3 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 28; O atributo "table" deve ser declarado para o tipo de elemento "id".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1253)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1917)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:742)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:499)
	... 4 more


07/07/2022 14:00:12
org.hibernate.PropertyNotFoundException: Could not find a getter for id in class beans.Cidade
	at org.hibernate.property.BasicPropertyAccessor.createGetter(BasicPropertyAccessor.java:282)
	at org.hibernate.property.BasicPropertyAccessor.getGetter(BasicPropertyAccessor.java:275)
	at org.hibernate.tuple.PropertyFactory.getGetter(PropertyFactory.java:168)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:44)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:123)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:434)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:109)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:55)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:226)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1294)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:26)
	at configuration.Principal.main(Principal.java:15)


07/07/2022 14:10:09
org.hibernate.PropertyNotFoundException: Could not find a getter for id in class beans.Cidade
	at org.hibernate.property.BasicPropertyAccessor.createGetter(BasicPropertyAccessor.java:282)
	at org.hibernate.property.BasicPropertyAccessor.getGetter(BasicPropertyAccessor.java:275)
	at org.hibernate.tuple.PropertyFactory.getGetter(PropertyFactory.java:168)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:44)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:123)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:434)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:109)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:55)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:226)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1294)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:26)
	at configuration.Principal.main(Principal.java:15)


07/07/2022 14:19:52
org.hibernate.MappingNotFoundException: resource: beans/Cidade.hbm.xml not found
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:533)
	at org.hibernate.cfg.Configuration.addClass(Configuration.java:586)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:15)


07/07/2022 14:20:36
org.hibernate.MappingNotFoundException: resource: beans/Cidade.hbm.xml not found
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:533)
	at org.hibernate.cfg.Configuration.addClass(Configuration.java:586)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:15)


07/07/2022 14:22:41
org.hibernate.InvalidMappingException: Could not parse mapping document from resource beans/Cidade.hbm.xml
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:539)
	at org.hibernate.cfg.Configuration.addClass(Configuration.java:586)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:15)
Caused by: org.hibernate.InvalidMappingException: Could not parse mapping document from invalid mapping
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:502)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:536)
	... 3 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 58; O atributo "ref" deve ser declarado para o tipo de elemento "property".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1253)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1917)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:763)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:499)
	... 4 more


07/07/2022 14:25:22
org.hibernate.PropertyNotFoundException: Could not find a getter for id in class beans.Cidade
	at org.hibernate.property.BasicPropertyAccessor.createGetter(BasicPropertyAccessor.java:282)
	at org.hibernate.property.BasicPropertyAccessor.getGetter(BasicPropertyAccessor.java:275)
	at org.hibernate.tuple.PropertyFactory.getGetter(PropertyFactory.java:168)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:44)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:123)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:434)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:109)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:55)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:226)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1294)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:26)
	at configuration.Principal.main(Principal.java:15)


07/07/2022 14:30:01
org.hibernate.InvalidMappingException: Could not parse mapping document from resource beans/Cidade.hbm.xml
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:539)
	at org.hibernate.cfg.Configuration.addClass(Configuration.java:586)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:24)
	at configuration.Principal.main(Principal.java:15)
Caused by: org.hibernate.InvalidMappingException: Could not parse mapping document from invalid mapping
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:502)
	at org.hibernate.cfg.Configuration.addResource(Configuration.java:536)
	... 3 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 60; O atributo "not-null" deve ser declarado para o tipo de elemento "id".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1253)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1917)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:742)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	at org.hibernate.cfg.Configuration.addInputStream(Configuration.java:499)
	... 4 more


07/07/2022 14:40:04
org.hibernate.PropertyNotFoundException: Could not find a getter for id in class beans.Cidade
	at org.hibernate.property.BasicPropertyAccessor.createGetter(BasicPropertyAccessor.java:282)
	at org.hibernate.property.BasicPropertyAccessor.getGetter(BasicPropertyAccessor.java:275)
	at org.hibernate.tuple.PropertyFactory.getGetter(PropertyFactory.java:168)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:44)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:123)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:434)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:109)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:55)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:226)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1294)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:26)
	at configuration.Principal.main(Principal.java:17)


07/07/2022 15:07:09
org.hibernate.PropertyNotFoundException: Could not find a getter for id in class beans.Cidade
	at org.hibernate.property.BasicPropertyAccessor.createGetter(BasicPropertyAccessor.java:282)
	at org.hibernate.property.BasicPropertyAccessor.getGetter(BasicPropertyAccessor.java:275)
	at org.hibernate.tuple.PropertyFactory.getGetter(PropertyFactory.java:168)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:44)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:123)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:434)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:109)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:55)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:226)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1294)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:26)
	at configuration.Principal.main(Principal.java:17)


07/07/2022 15:09:58
org.hibernate.PropertyNotFoundException: Could not find a getter for nome in class beans.Cidade
	at org.hibernate.property.BasicPropertyAccessor.createGetter(BasicPropertyAccessor.java:282)
	at org.hibernate.property.BasicPropertyAccessor.getGetter(BasicPropertyAccessor.java:275)
	at org.hibernate.mapping.Property.getGetter(Property.java:272)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildPropertyGetter(PojoEntityTuplizer.java:247)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:125)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:55)
	at org.hibernate.tuple.entity.EntityEntityModeToTuplizerMapping.<init>(EntityEntityModeToTuplizerMapping.java:56)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:295)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:434)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:109)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:55)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:226)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1294)
	at configuration.HibernateUtil.<clinit>(HibernateUtil.java:26)
	at configuration.Principal.main(Principal.java:17)
